#############SPI Configurate Setting##################
set_property BITSTREAM.CONFIG.SPI_BUSWIDTH 4 [current_design]
set_property CONFIG_MODE SPIx4 [current_design]
set_property BITSTREAM.CONFIG.CONFIGRATE 50 [current_design]

set_property BITSTREAM.GENERAL.COMPRESS TRUE [current_design]
set_property CFGBVS VCCO [current_design]
set_property CONFIG_VOLTAGE 3.3 [current_design]

#adc

set_property IOSTANDARD LVDS [get_ports {board1_adc1_data_p[11]}]
set_property IOSTANDARD LVDS [get_ports {board1_adc1_data_n[11]}]
set_property IOSTANDARD LVDS [get_ports {board1_adc1_data_p[10]}]
set_property IOSTANDARD LVDS [get_ports {board1_adc1_data_n[10]}]
set_property IOSTANDARD LVDS [get_ports {board1_adc1_data_p[9]}]
set_property IOSTANDARD LVDS [get_ports {board1_adc1_data_n[9]}]
set_property IOSTANDARD LVDS [get_ports {board1_adc1_data_p[8]}]
set_property IOSTANDARD LVDS [get_ports {board1_adc1_data_n[8]}]
set_property IOSTANDARD LVDS [get_ports {board1_adc1_data_p[7]}]
set_property IOSTANDARD LVDS [get_ports {board1_adc1_data_n[7]}]
set_property IOSTANDARD LVDS [get_ports {board1_adc1_data_p[6]}]
set_property IOSTANDARD LVDS [get_ports {board1_adc1_data_n[6]}]
set_property IOSTANDARD LVDS [get_ports {board1_adc1_data_p[5]}]
set_property IOSTANDARD LVDS [get_ports {board1_adc1_data_n[5]}]
set_property IOSTANDARD LVDS [get_ports {board1_adc1_data_p[4]}]
set_property IOSTANDARD LVDS [get_ports {board1_adc1_data_n[4]}]
set_property IOSTANDARD LVDS [get_ports {board1_adc1_data_p[3]}]
set_property IOSTANDARD LVDS [get_ports {board1_adc1_data_n[3]}]
set_property IOSTANDARD LVDS [get_ports {board1_adc1_data_p[2]}]
set_property IOSTANDARD LVDS [get_ports {board1_adc1_data_n[2]}]
set_property IOSTANDARD LVDS [get_ports {board1_adc1_data_p[1]}]
set_property IOSTANDARD LVDS [get_ports {board1_adc1_data_n[1]}]
set_property IOSTANDARD LVDS [get_ports {board1_adc1_data_p[0]}]
set_property IOSTANDARD LVDS [get_ports {board1_adc1_data_n[0]}]

set_property PACKAGE_PIN V22 [get_ports {board1_adc1_data_p[11]}]
set_property PACKAGE_PIN W25 [get_ports {board1_adc1_data_p[10]}]
set_property PACKAGE_PIN V21 [get_ports {board1_adc1_data_p[9]}]
set_property PACKAGE_PIN AA20 [get_ports {board1_adc1_data_p[8]}]
set_property PACKAGE_PIN Y26 [get_ports {board1_adc1_data_p[7]}]
set_property PACKAGE_PIN AB25 [get_ports {board1_adc1_data_p[6]}]
set_property PACKAGE_PIN AC26 [get_ports {board1_adc1_data_p[5]}]
set_property PACKAGE_PIN AA27 [get_ports {board1_adc1_data_p[4]}]
set_property PACKAGE_PIN AA22 [get_ports {board1_adc1_data_p[3]}]
set_property PACKAGE_PIN AD25 [get_ports {board1_adc1_data_p[2]}]
set_property PACKAGE_PIN AB24 [get_ports {board1_adc1_data_p[1]}]
set_property PACKAGE_PIN AB21 [get_ports {board1_adc1_data_p[0]}]

set_property IOSTANDARD LVDS [get_ports {board1_adc2_data_n[11]}]
set_property IOSTANDARD LVDS [get_ports {board1_adc2_data_p[11]}]
set_property IOSTANDARD LVDS [get_ports {board1_adc2_data_n[10]}]
set_property IOSTANDARD LVDS [get_ports {board1_adc2_data_p[10]}]
set_property IOSTANDARD LVDS [get_ports {board1_adc2_data_n[9]}]
set_property IOSTANDARD LVDS [get_ports {board1_adc2_data_p[9]}]
set_property IOSTANDARD LVDS [get_ports {board1_adc2_data_n[8]}]
set_property IOSTANDARD LVDS [get_ports {board1_adc2_data_p[8]}]
set_property IOSTANDARD LVDS [get_ports {board1_adc2_data_n[7]}]
set_property IOSTANDARD LVDS [get_ports {board1_adc2_data_p[7]}]
set_property IOSTANDARD LVDS [get_ports {board1_adc2_data_n[6]}]
set_property IOSTANDARD LVDS [get_ports {board1_adc2_data_p[6]}]
set_property IOSTANDARD LVDS [get_ports {board1_adc2_data_n[5]}]
set_property IOSTANDARD LVDS [get_ports {board1_adc2_data_p[5]}]
set_property IOSTANDARD LVDS [get_ports {board1_adc2_data_n[4]}]
set_property IOSTANDARD LVDS [get_ports {board1_adc2_data_p[4]}]
set_property IOSTANDARD LVDS [get_ports {board1_adc2_data_n[3]}]
set_property IOSTANDARD LVDS [get_ports {board1_adc2_data_p[3]}]
set_property IOSTANDARD LVDS [get_ports {board1_adc2_data_n[2]}]
set_property IOSTANDARD LVDS [get_ports {board1_adc2_data_p[2]}]
set_property IOSTANDARD LVDS [get_ports {board1_adc2_data_n[1]}]
set_property IOSTANDARD LVDS [get_ports {board1_adc2_data_p[1]}]
set_property IOSTANDARD LVDS [get_ports {board1_adc2_data_n[0]}]
set_property IOSTANDARD LVDS [get_ports {board1_adc2_data_p[0]}]

set_property PACKAGE_PIN AE28 [get_ports {board1_adc2_data_p[11]}]
set_property PACKAGE_PIN AD29 [get_ports {board1_adc2_data_p[10]}]
set_property PACKAGE_PIN AA34 [get_ports {board1_adc2_data_p[9]}]
set_property PACKAGE_PIN AC33 [get_ports {board1_adc2_data_p[8]}]
set_property PACKAGE_PIN AC34 [get_ports {board1_adc2_data_p[7]}]
set_property PACKAGE_PIN AE32 [get_ports {board1_adc2_data_p[6]}]
set_property PACKAGE_PIN AA29 [get_ports {board1_adc2_data_p[5]}]
set_property PACKAGE_PIN AE33 [get_ports {board1_adc2_data_p[4]}]
set_property PACKAGE_PIN AF33 [get_ports {board1_adc2_data_p[3]}]
set_property PACKAGE_PIN AB30 [get_ports {board1_adc2_data_p[2]}]
set_property PACKAGE_PIN AG31 [get_ports {board1_adc2_data_p[1]}]
set_property PACKAGE_PIN AF30 [get_ports {board1_adc2_data_p[0]}]


set_property IOSTANDARD LVDS_25 [get_ports {board2_adc1_data_p[11]}]
set_property IOSTANDARD LVDS_25 [get_ports {board2_adc1_data_n[11]}]
set_property IOSTANDARD LVDS_25 [get_ports {board2_adc1_data_p[10]}]
set_property IOSTANDARD LVDS_25 [get_ports {board2_adc1_data_n[10]}]
set_property IOSTANDARD LVDS_25 [get_ports {board2_adc1_data_p[9]}]
set_property IOSTANDARD LVDS_25 [get_ports {board2_adc1_data_n[9]}]
set_property IOSTANDARD LVDS_25 [get_ports {board2_adc1_data_p[8]}]
set_property IOSTANDARD LVDS_25 [get_ports {board2_adc1_data_n[8]}]
set_property IOSTANDARD LVDS_25 [get_ports {board2_adc1_data_p[7]}]
set_property IOSTANDARD LVDS_25 [get_ports {board2_adc1_data_n[7]}]
set_property IOSTANDARD LVDS_25 [get_ports {board2_adc1_data_p[6]}]
set_property IOSTANDARD LVDS_25 [get_ports {board2_adc1_data_n[6]}]
set_property IOSTANDARD LVDS_25 [get_ports {board2_adc1_data_p[5]}]
set_property IOSTANDARD LVDS_25 [get_ports {board2_adc1_data_n[5]}]
set_property IOSTANDARD LVDS_25 [get_ports {board2_adc1_data_p[4]}]
set_property IOSTANDARD LVDS_25 [get_ports {board2_adc1_data_n[4]}]
set_property IOSTANDARD LVDS_25 [get_ports {board2_adc1_data_p[3]}]
set_property IOSTANDARD LVDS_25 [get_ports {board2_adc1_data_n[3]}]
set_property IOSTANDARD LVDS_25 [get_ports {board2_adc1_data_p[2]}]
set_property IOSTANDARD LVDS_25 [get_ports {board2_adc1_data_n[2]}]
set_property IOSTANDARD LVDS_25 [get_ports {board2_adc1_data_p[1]}]
set_property IOSTANDARD LVDS_25 [get_ports {board2_adc1_data_n[1]}]
set_property IOSTANDARD LVDS_25 [get_ports {board2_adc1_data_p[0]}]
set_property IOSTANDARD LVDS_25 [get_ports {board2_adc1_data_n[0]}]
#14,13,11,12,9,7,8,10,4,5,6,2
set_property PACKAGE_PIN AH9 [get_ports {board2_adc1_data_p[11]}]
set_property PACKAGE_PIN AP11 [get_ports {board2_adc1_data_p[10]}]
set_property PACKAGE_PIN AD9 [get_ports {board2_adc1_data_p[9]}]
set_property PACKAGE_PIN AE13 [get_ports {board2_adc1_data_p[8]}]
set_property PACKAGE_PIN AE12 [get_ports {board2_adc1_data_p[7]}]
set_property PACKAGE_PIN AF9 [get_ports {board2_adc1_data_p[6]}]
set_property PACKAGE_PIN AD10 [get_ports {board2_adc1_data_p[5]}]
set_property PACKAGE_PIN AK12 [get_ports {board2_adc1_data_p[4]}]
set_property PACKAGE_PIN AD11 [get_ports {board2_adc1_data_p[3]}]
set_property PACKAGE_PIN AM12 [get_ports {board2_adc1_data_p[2]}]
set_property PACKAGE_PIN AH13 [get_ports {board2_adc1_data_p[1]}]
set_property PACKAGE_PIN AN13 [get_ports {board2_adc1_data_p[0]}]

set_property IOSTANDARD LVDS_25 [get_ports {board2_adc2_data_n[11]}]
set_property IOSTANDARD LVDS_25 [get_ports {board2_adc2_data_p[11]}]
set_property IOSTANDARD LVDS_25 [get_ports {board2_adc2_data_n[10]}]
set_property IOSTANDARD LVDS_25 [get_ports {board2_adc2_data_p[10]}]
set_property IOSTANDARD LVDS_25 [get_ports {board2_adc2_data_n[9]}]
set_property IOSTANDARD LVDS_25 [get_ports {board2_adc2_data_p[9]}]
set_property IOSTANDARD LVDS_25 [get_ports {board2_adc2_data_n[8]}]
set_property IOSTANDARD LVDS_25 [get_ports {board2_adc2_data_p[8]}]
set_property IOSTANDARD LVDS_25 [get_ports {board2_adc2_data_n[7]}]
set_property IOSTANDARD LVDS_25 [get_ports {board2_adc2_data_p[7]}]
set_property IOSTANDARD LVDS_25 [get_ports {board2_adc2_data_n[6]}]
set_property IOSTANDARD LVDS_25 [get_ports {board2_adc2_data_p[6]}]
set_property IOSTANDARD LVDS_25 [get_ports {board2_adc2_data_n[5]}]
set_property IOSTANDARD LVDS_25 [get_ports {board2_adc2_data_p[5]}]
set_property IOSTANDARD LVDS_25 [get_ports {board2_adc2_data_n[4]}]
set_property IOSTANDARD LVDS_25 [get_ports {board2_adc2_data_p[4]}]
set_property IOSTANDARD LVDS_25 [get_ports {board2_adc2_data_n[3]}]
set_property IOSTANDARD LVDS_25 [get_ports {board2_adc2_data_p[3]}]
set_property IOSTANDARD LVDS_25 [get_ports {board2_adc2_data_n[2]}]
set_property IOSTANDARD LVDS_25 [get_ports {board2_adc2_data_p[2]}]
set_property IOSTANDARD LVDS_25 [get_ports {board2_adc2_data_n[1]}]
set_property IOSTANDARD LVDS_25 [get_ports {board2_adc2_data_p[1]}]
set_property IOSTANDARD LVDS_25 [get_ports {board2_adc2_data_n[0]}]
set_property IOSTANDARD LVDS_25 [get_ports {board2_adc2_data_p[0]}]
#30,31,28,29,24,25,26,21,22,27,19,20
set_property PACKAGE_PIN G25 [get_ports {board2_adc2_data_p[11]}]
set_property PACKAGE_PIN H27 [get_ports {board2_adc2_data_p[10]}]
set_property PACKAGE_PIN J26 [get_ports {board2_adc2_data_p[9]}]
set_property PACKAGE_PIN K26 [get_ports {board2_adc2_data_p[8]}]
set_property PACKAGE_PIN L25 [get_ports {board2_adc2_data_p[7]}]
set_property PACKAGE_PIN M27 [get_ports {board2_adc2_data_p[6]}]
set_property PACKAGE_PIN L23 [get_ports {board2_adc2_data_p[5]}]
set_property PACKAGE_PIN R23 [get_ports {board2_adc2_data_p[4]}]
set_property PACKAGE_PIN R25 [get_ports {board2_adc2_data_p[3]}]
set_property PACKAGE_PIN L22 [get_ports {board2_adc2_data_p[2]}]
set_property PACKAGE_PIN T27 [get_ports {board2_adc2_data_p[1]}]
set_property PACKAGE_PIN T24 [get_ports {board2_adc2_data_p[0]}]

set_property PACKAGE_PIN P20 [get_ports fan_pwm]
set_property IOSTANDARD LVCMOS25 [get_ports fan_pwm]

set_property PACKAGE_PIN AK8 [get_ports rst_n]
set_property IOSTANDARD LVCMOS25 [get_ports rst_n]
set_property PACKAGE_PIN AK17 [get_ports sys_clk_p]
set_property IOSTANDARD DIFF_SSTL18_I [get_ports sys_clk_p]


set_property PACKAGE_PIN AA24 [get_ports board1_adc1_clk_p]
set_property PACKAGE_PIN W23 [get_ports board1_adc1_clk_ref]
set_property PACKAGE_PIN AC22 [get_ports board1_adc1_spi_ce]
set_property PACKAGE_PIN AC23 [get_ports board1_adc1_spi_io]
set_property PACKAGE_PIN W24 [get_ports board1_adc1_spi_sclk]
set_property PACKAGE_PIN AA32 [get_ports board1_adc2_clk_p]
set_property PACKAGE_PIN AC31 [get_ports board1_adc2_clk_ref]
set_property PACKAGE_PIN AC32 [get_ports board1_adc2_spi_ce]
set_property PACKAGE_PIN AF29 [get_ports board1_adc2_spi_io]
set_property PACKAGE_PIN AG29 [get_ports board1_adc2_spi_sclk]

set_property IOSTANDARD LVCMOS18 [get_ports board1_adc2_spi_sclk]
set_property IOSTANDARD LVCMOS18 [get_ports board1_adc2_spi_io]
set_property IOSTANDARD LVCMOS18 [get_ports board1_adc2_spi_ce]
set_property IOSTANDARD LVCMOS18 [get_ports board1_adc2_clk_ref]
set_property IOSTANDARD LVDS [get_ports board1_adc2_clk_n]
set_property IOSTANDARD LVDS [get_ports board1_adc2_clk_p]

set_property IOSTANDARD LVCMOS18 [get_ports board1_adc1_spi_sclk]
set_property IOSTANDARD LVCMOS18 [get_ports board1_adc1_spi_io]
set_property IOSTANDARD LVCMOS18 [get_ports board1_adc1_spi_ce]
set_property IOSTANDARD LVCMOS18 [get_ports board1_adc1_clk_ref]
set_property IOSTANDARD LVDS [get_ports board1_adc1_clk_n]
set_property IOSTANDARD LVDS [get_ports board1_adc1_clk_p]
#0,1,3p,3n,1n,18p,17p,17n,23p,23n
set_property PACKAGE_PIN AG11 [get_ports board2_adc1_clk_p]
set_property PACKAGE_PIN AF10 [get_ports board2_adc1_clk_ref]
set_property PACKAGE_PIN AK13 [get_ports board2_adc1_spi_ce]
set_property PACKAGE_PIN AL13 [get_ports board2_adc1_spi_io]
set_property PACKAGE_PIN AG10 [get_ports board2_adc1_spi_sclk]
set_property PACKAGE_PIN M25 [get_ports board2_adc2_clk_p]
set_property PACKAGE_PIN N24 [get_ports board2_adc2_clk_ref]
set_property PACKAGE_PIN M24 [get_ports board2_adc2_spi_ce]
set_property PACKAGE_PIN N22 [get_ports board2_adc2_spi_io]
set_property PACKAGE_PIN M22 [get_ports board2_adc2_spi_sclk]

set_property IOSTANDARD LVCMOS25 [get_ports board2_adc2_spi_sclk]
set_property IOSTANDARD LVCMOS25 [get_ports board2_adc2_spi_io]
set_property IOSTANDARD LVCMOS25 [get_ports board2_adc2_spi_ce]
set_property IOSTANDARD LVCMOS25 [get_ports board2_adc2_clk_ref]
set_property IOSTANDARD LVDS_25 [get_ports board2_adc2_clk_n]
set_property IOSTANDARD LVDS_25 [get_ports board2_adc2_clk_p]

set_property IOSTANDARD LVCMOS25 [get_ports board2_adc1_spi_sclk]
set_property IOSTANDARD LVCMOS25 [get_ports board2_adc1_spi_io]
set_property IOSTANDARD LVCMOS25 [get_ports board2_adc1_spi_ce]
set_property IOSTANDARD LVCMOS25 [get_ports board2_adc1_clk_ref]
set_property IOSTANDARD LVDS_25 [get_ports board2_adc1_clk_n]
set_property IOSTANDARD LVDS_25 [get_ports board2_adc1_clk_p]


create_clock -period 8.000 -name adc1_clk_p -waveform {0.000 4.000} [get_ports board1_adc1_clk_p]
create_clock -period 8.000 -name adc2_clk_p -waveform {0.000 4.000} [get_ports board1_adc2_clk_p]
create_clock -period 8.000 -name adc1_clk_p -waveform {0.000 4.000} [get_ports board2_adc1_clk_p]
create_clock -period 8.000 -name adc2_clk_p -waveform {0.000 4.000} [get_ports board2_adc2_clk_p]



############## SD define##################
set_property IOSTANDARD LVCMOS25 [get_ports sd_dclk]
set_property PACKAGE_PIN AN8 [get_ports sd_dclk]

set_property IOSTANDARD LVCMOS25 [get_ports sd_ncs]
set_property PACKAGE_PIN AK10 [get_ports sd_ncs]

set_property IOSTANDARD LVCMOS25 [get_ports sd_mosi]
set_property PACKAGE_PIN AL9 [get_ports sd_mosi]

set_property IOSTANDARD LVCMOS25 [get_ports sd_miso]
set_property PACKAGE_PIN AL8 [get_ports sd_miso]






set_false_path -from [get_pins {adc_board2/IBUFDS_DATAS[10].IDDR_adc1_data/CLK}] -to [get_pins {data/adc_E_data_sample/uut_0/inst/ila_core_inst/shifted_data_in_reg[7][5]_srl8/D}]
set_false_path -from [get_pins {adc_board2/IBUFDS_DATAS[9].IDDR_adc1_data/CLK}] -to [get_pins {data/adc_E_data_sample/cnt2_reg[3]/D}]
set_false_path -from [get_pins {adc_board2/IBUFDS_DATAS[9].IDDR_adc1_data/CLK}] -to [get_pins {data/adc_E_data_sample/uut_0/inst/ila_core_inst/shifted_data_in_reg[7][4]_srl8/D}]
set_false_path -from [get_pins {adc_board2/IBUFDS_DATAS[10].IDDR_adc1_data/CLK}] -to [get_pins {data/adc_E_data_sample/cnt2_reg[4]/D}]
set_false_path -from [get_pins {adc_board2/IBUFDS_DATAS[10].IDDR_adc1_data/CLK}] -to [get_pins {data/adc_E_data_sample/cnt2_reg[0]/D}]
set_false_path -from [get_pins {adc_board2/IBUFDS_DATAS[9].IDDR_adc1_data/CLK}] -to [get_pins {data/adc_E_data_sample/cnt2_reg[1]/D}]
set_false_path -from [get_pins {adc_board2/IBUFDS_DATAS[10].IDDR_adc1_data/CLK}] -to [get_pins {data/adc_E_data_sample/cnt1_reg[0]/D}]
set_false_path -from [get_pins {adc_board2/IBUFDS_DATAS[9].IDDR_adc1_data/CLK}] -to [get_pins {data/adc_E_data_sample/cnt1_reg[1]/D}]
set_false_path -from [get_pins {adc_board2/IBUFDS_DATAS[9].IDDR_adc1_data/CLK}] -to [get_pins {data/adc_E_data_sample/cnt1_reg[2]/D}]
set_false_path -from [get_pins {adc_board2/IBUFDS_DATAS[9].IDDR_adc1_data/CLK}] -to [get_pins {data/adc_E_data_sample/uut_0/inst/ila_core_inst/shifted_data_in_reg[7][4]_srl8/D}]

set_false_path -from [get_clocks adc1_clk_p] -to [get_clocks -of_objects [get_pins clk_for_all/inst/mmcme3_adv_inst/CLKOUT1]]
set_false_path -from [get_clocks adc2_clk_p] -to [get_clocks -of_objects [get_pins clk_for_all/inst/mmcme3_adv_inst/CLKOUT1]]

set_false_path -from [get_pins clk_for_all/inst/mmcme3_adv_inst/CLKOUT1] -to [get_pins {data/adc_G_data_package/uut_3/inst/ila_core_inst/shifted_data_in_reg[7][79]_srl8/D}]
set_false_path -from [get_pins clk_for_all/inst/mmcme3_adv_inst/CLKOUT1] -to [get_pins {data/adc_H_data_package/uut_3/inst/ila_core_inst/shifted_data_in_reg[7][79]_srl8/D}]
set_false_path -from [get_pins clk_for_all/inst/mmcme3_adv_inst/CLKOUT1] -to [get_pins {data/adc_G_data_package/uut_3/inst/ila_core_inst/shifted_data_in_reg[7][79]_srl8/D}]
set_false_path -from [get_pins clk_for_all/inst/mmcme3_adv_inst/CLKOUT1] -to [get_pins {data/adc_B_data_package/uut_3/inst/ila_core_inst/shifted_data_in_reg[7][79]_srl8/D}]
set_false_path -from [get_pins clk_for_all/inst/mmcme3_adv_inst/CLKOUT1] -to [get_pins {data/adc_D_data_package/uut_3/inst/ila_core_inst/shifted_data_in_reg[7][79]_srl8/D}]
set_false_path -from [get_pins clk_for_all/inst/mmcme3_adv_inst/CLKOUT1] -to [get_pins {data/adc_F_data_package/uut_3/inst/ila_core_inst/shifted_data_in_reg[7][79]_srl8/D}]
set_false_path -from [get_pins clk_for_all/inst/mmcme3_adv_inst/CLKOUT1] -to [get_pins {data/adc_C_data_package/uut_3/inst/ila_core_inst/shifted_data_in_reg[7][79]_srl8/D}]
set_false_path -from [get_pins clk_for_all/inst/mmcme3_adv_inst/CLKOUT1] -to [get_pins {data/adc_A_data_package/uut_3/inst/ila_core_inst/shifted_data_in_reg[7][79]_srl8/D}]
set_false_path -from [get_pins clk_for_all/inst/mmcme3_adv_inst/CLKOUT1] -to [get_pins {data/adc_E_data_package/uut_3/inst/ila_core_inst/shifted_data_in_reg[7][79]_srl8/D}]
set_false_path -from [get_pins clk_for_all/inst/mmcme3_adv_inst/CLKOUT1] -to [get_pins {data/adc_D_data_package/uut_3/inst/ila_core_inst/u_trig/U_TM/N_DDR_MODE.G_NMU[12].U_M/allx_typeA_match_detection.ltlib_v1_0_0_allx_typeA_inst/probeDelay1_reg[0]/D}]
set_false_path -from [get_pins clk_for_all/inst/mmcme3_adv_inst/CLKOUT1] -to [get_pins {data/adc_E_data_package/uut_3/inst/ila_core_inst/u_trig/U_TM/N_DDR_MODE.G_NMU[12].U_M/allx_typeA_match_detection.ltlib_v1_0_0_allx_typeA_inst/probeDelay1_reg[0]/D}]

set_false_path -from [get_pins clk_for_all/inst/mmcme3_adv_inst/CLKOUT1] -to [get_pins {data/adc_A_data_package/uut_3/inst/ila_core_inst/u_trig/U_TM/N_DDR_MODE.G_NMU[12].U_M/allx_typeA_match_detection.ltlib_v1_0_0_allx_typeA_inst/probeDelay1_reg[0]/D}]
set_false_path -from [get_pins clk_for_all/inst/mmcme3_adv_inst/CLKOUT1] -to [get_pins {data/adc_G_data_package/uut_3/inst/ila_core_inst/u_trig/U_TM/N_DDR_MODE.G_NMU[12].U_M/allx_typeA_match_detection.ltlib_v1_0_0_allx_typeA_inst/probeDelay1_reg[0]/D}]
set_false_path -from [get_pins clk_for_all/inst/mmcme3_adv_inst/CLKOUT1] -to [get_pins {data/adc_B_data_package/uut_3/inst/ila_core_inst/u_trig/U_TM/N_DDR_MODE.G_NMU[12].U_M/allx_typeA_match_detection.ltlib_v1_0_0_allx_typeA_inst/probeDelay1_reg[0]/D}]
set_false_path -from [get_pins clk_for_all/inst/mmcme3_adv_inst/CLKOUT1] -to [get_pins {data/adc_F_data_package/uut_3/inst/ila_core_inst/u_trig/U_TM/N_DDR_MODE.G_NMU[12].U_M/allx_typeA_match_detection.ltlib_v1_0_0_allx_typeA_inst/probeDelay1_reg[0]/D}]
set_false_path -from [get_pins clk_for_all/inst/mmcme3_adv_inst/CLKOUT1] -to [get_pins {data/adc_C_data_package/uut_3/inst/ila_core_inst/u_trig/U_TM/N_DDR_MODE.G_NMU[12].U_M/allx_typeA_match_detection.ltlib_v1_0_0_allx_typeA_inst/probeDelay1_reg[0]/D}]
set_false_path -from [get_pins clk_for_all/inst/mmcme3_adv_inst/CLKOUT1] -to [get_pins {data/adc_H_data_package/uut_3/inst/ila_core_inst/u_trig/U_TM/N_DDR_MODE.G_NMU[12].U_M/allx_typeA_match_detection.ltlib_v1_0_0_allx_typeA_inst/probeDelay1_reg[0]/D}]
set_false_path -from [get_pins clk_for_all/inst/mmcme3_adv_inst/CLKOUT1] -to [get_pins {data/adc_A_data_package/uut_3/inst/ila_core_inst/u_trig/U_TM/N_DDR_MODE.G_NMU[12].U_M/allx_typeA_match_detection.ltlib_v1_0_0_allx_typeA_inst/probeDelay1_reg[0]/D}]
set_false_path -from [get_pins clk_for_all/inst/mmcme3_adv_inst/CLKOUT1] -to [get_pins {data/adc_G_data_package/uut_3/inst/ila_core_inst/u_trig/U_TM/N_DDR_MODE.G_NMU[12].U_M/allx_typeA_match_detection.ltlib_v1_0_0_allx_typeA_inst/probeDelay1_reg[0]/D}]
set_false_path -from [get_pins clk_for_all/inst/mmcme3_adv_inst/CLKOUT1] -to [get_pins {data/adc_B_data_package/uut_3/inst/ila_core_inst/u_trig/U_TM/N_DDR_MODE.G_NMU[12].U_M/allx_typeA_match_detection.ltlib_v1_0_0_allx_typeA_inst/probeDelay1_reg[0]/D}]
set_false_path -from [get_pins clk_for_all/inst/mmcme3_adv_inst/CLKOUT1] -to [get_pins {data/adc_F_data_package/uut_3/inst/ila_core_inst/u_trig/U_TM/N_DDR_MODE.G_NMU[12].U_M/allx_typeA_match_detection.ltlib_v1_0_0_allx_typeA_inst/probeDelay1_reg[0]/D}]
set_false_path -from [get_pins clk_for_all/inst/mmcme3_adv_inst/CLKOUT1] -to [get_pins {data/adc_C_data_package/uut_3/inst/ila_core_inst/u_trig/U_TM/N_DDR_MODE.G_NMU[12].U_M/allx_typeA_match_detection.ltlib_v1_0_0_allx_typeA_inst/probeDelay1_reg[0]/D}]
set_false_path -from [get_pins clk_for_all/inst/mmcme3_adv_inst/CLKOUT1] -to [get_pins {data/adc_H_data_package/uut_3/inst/ila_core_inst/u_trig/U_TM/N_DDR_MODE.G_NMU[12].U_M/allx_typeA_match_detection.ltlib_v1_0_0_allx_typeA_inst/probeDelay1_reg[0]/D}]


set_property C_CLK_INPUT_FREQ_HZ 300000000 [get_debug_cores dbg_hub]
set_property C_ENABLE_CLK_DIVIDER false [get_debug_cores dbg_hub]
set_property C_USER_SCAN_CHAIN 1 [get_debug_cores dbg_hub]
connect_debug_port dbg_hub/clk [get_nets board2_adc2_clk_ref_OBUF]
