# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/new/adc_ethernet.xdc

# IP: ip/sys_clk_mmcm/sys_clk_mmcm.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==sys_clk_mmcm || ORIG_REF_NAME==sys_clk_mmcm} -quiet] -quiet
